Return-Path: <cgroups-owner@vger.kernel.org>
X-Original-To: lists+cgroups@lfdr.de
Delivered-To: lists+cgroups@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id C574B3F1C20
	for <lists+cgroups@lfdr.de>; Thu, 19 Aug 2021 17:02:48 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S240672AbhHSPDY (ORCPT <rfc822;lists+cgroups@lfdr.de>);
        Thu, 19 Aug 2021 11:03:24 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:51150 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S240652AbhHSPDX (ORCPT
        <rfc822;cgroups@vger.kernel.org>); Thu, 19 Aug 2021 11:03:23 -0400
Received: from mail-vk1-xa2b.google.com (mail-vk1-xa2b.google.com [IPv6:2607:f8b0:4864:20::a2b])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 9E63BC061575
        for <cgroups@vger.kernel.org>; Thu, 19 Aug 2021 08:02:47 -0700 (PDT)
Received: by mail-vk1-xa2b.google.com with SMTP id 1so1672275vkk.1
        for <cgroups@vger.kernel.org>; Thu, 19 Aug 2021 08:02:47 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:reply-to:from:date:message-id:subject:to;
        bh=ovRohL0S09O0g2yqlE9MP24xrDvA30mKbGD9YeR3sEY=;
        b=HySdqSoW6vC5vNTWVf5OA/1CIgpVFQGLDcH3ZyDA8s/YCVom6i9N5My0zGwdVv4gKF
         oDtaeA11DpdPzgAILj/FcK13ofOmddzIPRFi8hCPFPrSxO0RoNKYc/QYBpvLmvBYW0MR
         Mb+6pwSNotHNXaoumk6dHo3O4BGvpGuD8afPO/nVx8Jsv3qI//ZtuDoBn0UPJFWunD80
         4c/Mmd1EKN3L1uiwOTCfxxU0bXdFfv6+WQVe+ToiKkA5xkK7Zozg8o0gon7NADbpQBan
         x8cxOJWjg2CzjTjn6rwHxAP/rHdvqpeiHguzhYI7fP+mPBPZ3ZSIek8PfsdHTfK7gOMy
         Hwow==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:reply-to:from:date:message-id
         :subject:to;
        bh=ovRohL0S09O0g2yqlE9MP24xrDvA30mKbGD9YeR3sEY=;
        b=Ang3mkpecQ7TAT+bqwNNcd1ntqBQfdZTRWKN68mJZjjfPCYQK3GiiDYRt5MOXnW12d
         ewE3m6jhAfi6mSlcnPkRmTcd+SE3PkyUvCtJxIQxix6g6FhtjtrjmB5bJSE4YC9474ux
         qYvJ8RXYsPZGMkO4PqAxoOND8xJ8YIkozDd5DBncdjjVeEpx3JxeFLew8rzhXBmEG/J+
         wmQEOOBlFGAOcBtSeEiDtpiDycUtVkt5uNM3tvOh93EnVXq4Riy9nLyRYF/0/LwoHtcb
         1dgCbWe6uUXXdEohFXFQpjgKm6psA0reAokGlqKt8lT5k/d44WnEev7KuQT7PacgeMU4
         DhRg==
X-Gm-Message-State: AOAM530B/umMHzqB/CsimptnZ1kOPfTH3JgjiGYD5rbmsSrEd5KnOOBR
        3RQEV5W2BtnTdzktfczqMlgproAJjBwe0TudHnI=
X-Google-Smtp-Source: ABdhPJwL7rrbK60LUxg854teaXvJZg3xQqWzerSUkyVCP4eKcS+45hufIJWbT9OIB2gPbUQ3oOycT3RQtJCiNc4cyWM=
X-Received: by 2002:a1f:308d:: with SMTP id w135mr11513253vkw.15.1629385366678;
 Thu, 19 Aug 2021 08:02:46 -0700 (PDT)
MIME-Version: 1.0
Received: by 2002:a67:cb08:0:0:0:0:0 with HTTP; Thu, 19 Aug 2021 08:02:46
 -0700 (PDT)
Reply-To: rraya9989@gmail.com
From:   Louisa Besson <mrsraya001@gmail.com>
Date:   Thu, 19 Aug 2021 15:02:46 +0000
Message-ID: <CAGq9nGNfF8ytUc2coHDOS7gsLpL3LLMDNUfVrWZcvsJOOhvPqA@mail.gmail.com>
Subject: DECISION
To:     rraya9989@gmail.com
Content-Type: text/plain; charset="UTF-8"
Precedence: bulk
List-ID: <cgroups.vger.kernel.org>
X-Mailing-List: cgroups@vger.kernel.org

MY SINCERE GREETINGS,

HOW ARE YOU DOING TODAY? I AM MRS.LOUISA BESSON FROM FRANCE; I HAVE
DECIDED TO DONATE WHAT I HAVE TO YOU /CHURCHES/ MOTHERLESS BABIES/LESS
PRIVILEGED/WIDOWS' BECAUSE I AM DYING AND DIAGNOSED WITH CANCER. I
HAVE BEEN TOUCHED BY GOD ALMIGHTY TO DONATE FROM WHAT I HAVE INHERITED
FROM MY LATE HUSBAND TO YOU FOR THE GOOD WORK OF GOD ALMIGHTY. I HAVE
ASKED ALMIGHTY GOD TO FORGIVE ME AND BELIEVE HE HAS, BECAUSE HE IS A
MERCIFUL GOD I WILL BE GOING IN FOR AN OPERATION SOON.

I DECIDED TO DONATE THE SUM OF ($8.5 MILLION DOLLARS) TO YOU FOR THE
GOOD WORK OF GOD ALMIGHTY, AND ALSO TO HELP THE MOTHERLESS AND LESS
PRIVILEGED AND ALSO FOR ASSISTANCE OF THE WIDOWS. AS SOON AS I READ
FROM YOU, I SHALL GIVE YOU INFO ON WHAT I NEED FROM YOU, THEN YOU WILL
CONTACT THE BANK AND TELL THEM I HAVE WILLED MY INHERITANCE TO YOU BY
QUOTING MY PERSONAL FILE ROUTING AND ACCOUNT INFORMATION TO YOU FOR
GOOD, EFFECTIVE AND PRUDENT WORK. I KNOW I DON'T KNOW YOU BUT I HAVE
BEEN DIRECTED TO DO THIS BY GOD ALMIGHTY.

PLEASE I WILL NEED YOU TO RESPECT MY DECISION AND KEEP EVERY PROCESS
OF THIS TRANSFER CONFIDENTIAL / TOP SECRET UNTIL EVERY PROCESS IS
FINALIZED, BEFORE TAKING FAMILY AND FRIENDS FOR THANKSGIVING. IF YOU
ARE INTERESTED IN CARRYING OUT THIS TASK, I WILL NEED YOU TO GET BACK
TO ME AND ANSWER THE BELOW QUESTIONS,

1). THAT YOU ARE IN A POSITION TO BE TRUSTED WITH SUCH A LARGE AMOUNT
OF FUNDS, AND THAT YOU HAVE A HEART FOR CHARITY AND THUS WOULD NOT
HAVE ANY PROBLEMS LOCATING THE RIGHT CHARITY AND HUMAN AID GROUPS TO
DISBURSE THE FUND TO. IT WOULD BE NICE TO KNOW WHAT CHARITIES YOU HAVE
IN MIND TO DONATE THE MONEY TO?

2). THAT YOU ARE WILLING TO CONTACT THE BANK HOLDING THE DEPOSIT TO
DISCUSS THE TERMS OF RELEASING THE FUNDS TO YOU?

3). THAT YOU PROMISE TO RESPECT MY DECISION AND KEEP EVERY PROCESS OF
THIS TRANSFER CONFIDENTIAL / TOP SECRET UNTIL EVERY PROCESS IS
FINALIZED?

4). THAT YOU FULLY UNDERSTAND THIS TRANSACTION AND YOU ARE READY TO
PROCEED UNDER THESE TERMS?

I WISH YOU ALL THE BEST AND MAY THE GOOD LORD BLESS YOU ABUNDANTLY.

YOURS FAITHFULLY,
MRS.LOUISA BESSON
